# Parameters' values in this config file are set to the default values used during testing. 
# Feel free to change the parameters' values as you see fit.
priors:
  lambda0:
    dist: 'unif'
    hyperparameters:
    - min: 0.1
    - max: 0.1
  lambda1:
    dist: 'unif'
    hyperparameters:
    - min: 0.2
    - max: 0.2
  mu0:
    dist: 'unif'
    hyperparameters:
    - min: 0.003
    - max: 0.003
  mu1:
    dist: 'unif'
    hyperparameters:
    - min: 0.003
    - max: 0.003
  q01:
    dist: 'unif'
    hyperparameters:
    - min: 0.01
    - max: 0.01
  q10:
    dist: 'unif'
    hyperparameters:
    - min: 0.01
    - max: 0.01
proposals:
  lambda0:
    dist: 'unif'
    parameters:
    - min: 0.1
    - max: 0.1
  lambda1:
    dist: 'unif'
    parameters:
    - min: 0.2
    - max: 0.2
  mu0:
    dist: 'unif'
    parameters:
    - min: 0.003
    - max: 0.003
  mu1:
    dist: 'unif'
    parameters:
    - min: 0.003
    - max: 0.003
  q01:
    dist: 'unif'
    parameters:
    - min: 0.01
    - max: 0.01
  q10:
    dist: 'unif'
    parameters:
    - min: 0.01
    - max: 0.01
smc:
  nparticle: 100
  nsample: 5
  ess.tolerance: 50.0
  final.accept.rate: 0.1
  final.epsilon: 0.1
  quality: 0.95
  step.tolerance: 1.e-5
kernel:
  decay.factor: 0.2
  rbf.variance: 100.0
  sst.control: 1.0
  norm.mode: 'NONE'
