# Parameters' values in this config file are set to the default values used during testing. 
# Feel free to change the parameters' values as you see fit.
priors:
  Ne.tau:
    dist: 'lnorm'
    hyperparameters:
    - meanlog: 5
    - sdlog: 2
proposals:
  Ne.tau:
    dist: 'norm'
    parameters:
    - mean: 0
    - sd: 50
smc:
  nparticle: 100
  nsample: 5
  ess.tolerance: 50.0
  final.accept.rate: 0.1
  final.epsilon: 0.1
  quality: 0.95
  step.tolerance: 1.e-5
kernel:
  decay.factor: 0.2
  rbf.variance: 100.0
  sst.control: 1.0
  norm.mode: 'NONE'
