# Parameters' values in this config file are set to the default values used during testing. 
# Feel free to change the parameters' values as you see fit.
priors:
  't.end':
    dist: 'norm'
    hyperparameters:
    - mean: 50
    - sd: 5
  'N':
    dist: 'norm'
    hyperparameters:
    - mean: 5000
    - sd: 100
  'beta':
    dist: 'gamma'
    hyperparameters:
    - shape: 50
    - rate: 1
  'gamma':
    dist: 'gamma'
    hyperparameters:
    - shape: 50
    - rate: 1
  'mu':
    dist: 'gamma'
    hyperparameters:
    - shape: 50
    - rate: 1
constraints:
  - ''
proposals:
  't.end':
    dist: 'norm'
    parameters:
    - mean: 50
    - sd: 5
  'N':
    dist: 'norm'
    parameters:
    - mean: 1000
    - sd: 500
  'beta':
    dist: 'gamma'
    parameters:
    - shape: 50
    - rate: 1
  'gamma':
    dist: 'gamma'
    parameters:
    - shape: 20
    - rate: 1
  'mu':
    dist: 'gamma'
    parameters:
    - shape: 20
    - rate: 1
smc:
  nparticle: 500
  nsample: 3
  ess.tolerance: 50.0
  final.accept.rate: 0.1
  final.epsilon: 0.1
  quality: 0.95
  step.tolerance: 1.e-5
distances:
  'kernel.dist':
    weight: 1.0
    decay.factor: 0.02
    rbf.variance: 100.0
    sst.control: 1.0
    norm.mode: 'NONE'
